### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by Zaid-Ajaj** [Krzysztof-Cieslak/FSharp.Analyzers.SDK#2]
Hello @Krzysztof-Cieslak, 

This project looks very interesting :smile: is this ready for use with Ionide? Is there any sample out there to checkout?

**Comment by Krzysztof-Cieslak** [comment]
The basic usage have been described in the blog pos here - https://link.medium.com/vUdpTi1UOU. 

And, yes, Ionide/FSAC are supporting it.

**Comment by Zaid-Ajaj** [comment]
Great, I will check it out, thanks!
